title: "Etherium"
markdown: kramdown

colors:
  sun: "#ff9f0e"
  lilac: "#816fa5"
  pink: "#ff84c1"
  dark: "#35006c"
  azure: "#07c6e6"
  clear: "#FFFFFF"
  golden: "#ffcd04"
  radiant: "#ffff6a"
  emerald: "#05b1a0"
  crimson: "#aa002e"
  green: "#0ab320"

include:
  - search.json